# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.User'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.User'),
        ),
    ]
